name: Go API CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-build:
    name: Run Tests & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26.1'

      - name: Download Dependencies
        run: go mod download

      - name: Run Unit & Integration Tests
        run: go test -v ./...

      - name: Verify Build
        run: go build -o api ./cmd/api/main.go